/**
 * Summary: Chooses a random league of legend champ. MUST BE UPDATED FOR EVERY NEW CHAMP!
 * 
 * Useage: !randomchamp
 */
exports.run = (client, message, args, ops) => {

    var responses =
    [
        'Zyra, Rise of the Thorns',
        'Zoe the Aspect of Twilight',
        'Zilean the Chronokeeper',
        'Ziggs the Hexplosives Expert',
        'Zed the Master of Shadows',
        'Zac the Secret Weapon',
        'Stebbers the Ghey Chink',
        'Yuumi the Magical Cat',
        'Yorick, Shepherd of Souls',
        'Yasuo the Unforgiven',
        'Xin Zhao the Seneschal of Demacia',
        'Xerath the Magus Ascendant',
        'Xayah the Rebel',
        'Wukong the Monkey King',
        'Warwick the Uncaged Wrath of Zaun',
        `Volibear the Thunder's Roar`,
        'Vladimir the Crimson Reaper',
        'Viktor the Machine Herald',
        'Vi the Piltover Enforcer',
        `Vel'Koz the Eye of the Void`,
        'Veigar the Tiny Master of Evil',
        'Vayne the Night Hunter',
        'Varus the Arrow of Retribution',
        'Urgot the Dreadnought',
        'Udyr the Spirit Walker',
        'Twitch the Plague Rat',
        'Twisted Fate the Card Master',
        'Tryndamere the Barbarian King',
        'Trundle the Troll King',
        'Tristana the Yordle Gunner',
        'Thresh the Chain Warden',
        'Teemo the Swift Scout',
        'Taric the Shield of Valoran',
        `Talon the Blade's Shadow`,
        'Taliyah the Stoneweaver',
        'Tahm Kench the River King',
        'Syndra the Dark Sovereign',
        'Sylas the Unshackled',
        'Swain the Noxian Grand General',
        'Soraka the Starchild',
        'Sona, Maven of the Strings',
        'Skarner the Crystal Vanguard',
        'Sivir the Battle Mistress',
        'Sion the Undead Juggernaut',
        'Singed the Mad Chemist',
        'Shyvana the Half-Dragon',
        'Shen the Eye of Twilight',
        'Shaco the Demon Jester',
        'Sejuani, Fury of the North',
        'Ryze the Rune Mage',
        'Rumble the Mechanized Menace',
        'Riven the Exile',
        'Rengar the Pridestalker',
        'Renekton the Butcher of the Sands',
        `Rek'Sai the Void Burrower`,
        'Rammus the Armordillo',
        'Rakan the Charmer',
        `Quinn, Demacia's Wings`,
        'Qiyana, Empress of the Elements',
        'Pyke the Bloodharbor Ripper',
        'Poppy, Keeper of the Hammer',
        'Pantheon the Unbreakable Spear',
        'Ornn the Fire Below The Mountain',
        'Orianna the Lady of Clockwork',
        'Olaf the Berserker',
        'Nunu the Boy and his Yeti',
        'Nocturne the Eternal Nightmare',
        'Nidalee the Bestial Huntress',
        'Neeko the Curious Chameleon',
        'Nautilus the Titan of the Depths',
        'Nasus the Curator of the Sands',
        'Nami the Tidecaller',
        'Morgana the Fallen',
        'Mordekaiser the Iron Revenant',
        'Miss Fortune the Bounty Hunter',
        'Master Yi the Wuju Bladesman',
        'Maokai the Twisted Treant',
        'Malzahar the Prophet of the Void',
        'Malphite, Shard of the Monolith',
        'Lux the Lady of Luminosity',
        'Lulu the Fae Sorceress',
        'Lucian the Purifier',
        'Lissandra the Ice Witch',
        'Leona the Radiant Dawn',
        'Lee Sin the Blind Monk',
        'LeBlanc the Deceiver',
        `Kog'Maw the Mouth of the Abyss`,
        'Kled the Cantankerous Cavalier',
        'Kindred the Eternal Hunters',
        `Kha'Zix the Voidreaver`,
        'Kennen the Heart of the Tempest',
        'Kayn the Shadow Reaper',
        'Kayle the Righteous',
        'Katarina the Sinister Blade',
        'Kassadin the Void Walker',
        'Karthus the Deathsinger',
        'Karma the Enlightened One',
        'Kalista the Spear of Vengeance',
        `Kai'Sa, Daughter of the Void`,
        'Jinx the Loose Cannon',
        'Jhin the Virtuoso',
        'Jayce the Defender of Tomorrow',
        'Jax, Grandmaster at Arms',
        'Jarvan IV the Exemplar of Demacia',
        `Janna the Storm's Fury`,
        'Ivern the Green Father',
        'Irelia the Blade Dancer',
        'Illaoi the Kraken Priestess',
        'Heimerdinger the Revered Inventor',
        'Hecarim the Shadow of War',
        'Graves the Outlaw',
        'Gragas the Rabble Rouser',
        'Gnar the Missing Link',
        'Garen the Might of Demacia',
        'Gangplank the Saltwater Scourge',
        'Galio the Colossus',
        'Fizz the Tidal Trickster',
        'Fiora the Grand Duelist',
        'Fiddlesticks the Harbinger of Doom',
        'Ezreal the Prodigal Explorer',
        `Evelynn, Agony's Embrace`,
        'Elise the Spider Queen',
        'Ekko the Boy Who Shattered Time',
        'Draven the Glorious Executioner',
        'Dr. Mundo the Madman of Zaun',
        'Diana, Scorn of the Moon',
        'Darius the Hand of Noxus',
        'Corki the Daring Bombardier',
        `Cho'Gath the Terror of the Void`,
        `Cassiopeia the Serpent's Embrace`,
        'Camille the Steel Shadow',
        'Caitlyn the Sheriff of Piltover',
        'Braum the Heart of the Freljord',
        'Brand the Burning Vengeance',
        'Blitzcrank the Great Steam Golem',
        'Bard the Wandering Caretaker',
        'Azir the Emperor of the Sands',
        'Aurelion Sol the Star Forger',
        'Ashe the Frost Archer',
        'Annie the Dark Child',
        'Anivia the Cryophoenix',
        'Amumu the Sad Mummy',
        'Alistar the Minotaur',
        'Akali the Rogue Assassin',
        'Ahri the Nine-Tailed Fox',
        'Aatrox the Darkin Blade',
        


    ]

    message.channel.send("Eenie meenie miney mo...Now you get to play this hoe:\n")
    return message.channel.send(responses[Math.floor(Math.random() * responses.length)])
}