exports.TOKEN = 'DISCORD APP TOKEN HERE';

exports.PREFIX = '!';

exports.GOOGLE_API_KEY = 'GOOGLE YT DATA API KEY HERE';

exports.GUILDID = 'DISCORD SERVER ID';

exports.TOTALUSERSID = 'CHANNEL TO KEEP TRACK OF TOTAL USER ID';

exports.MEMBERCOUNTID = 'CHANNEL TO KEEP TRACK OF MEMBER COUNT ID';

exports.BOTCOUNTID = 'CHANNEL TO KEEP TRACK OF BOT COUNT ID';

exports.OWNERID = 'BOT OWNER DISCORD ID';

exports.GENERALCHANNEL = 'DISCORD SERVER GENERAL CHANNEL ID';

